export interface EmojiItem {
  char: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: string; // Emoji character representing category
  emojis: EmojiItem[];
}

export const EMOJI_DATASET: EmojiCategory[] = [
  {
    id: "smileys",
    name: "Smileys & People",
    icon: "😀",
    emojis: [
      { char: "😀", name: "grinning face", keywords: ["smile", "happy", "joy"] },
      { char: "😃", name: "grinning face with big eyes", keywords: ["smile", "happy", "joy", "open mouth"] },
      { char: "😄", name: "grinning face with smiling eyes", keywords: ["smile", "happy", "joy", "laugh"] },
      { char: "😁", name: "beaming face with smiling eyes", keywords: ["smile", "grin", "happy", "teeth"] },
      { char: "😆", name: "grinning squinting face", keywords: ["laugh", "haha", "happy", "squint"] },
      { char: "😅", name: "grinning face with sweat", keywords: ["hot", "sweat", "laugh", "relief"] },
      { char: "🤣", name: "rolling on the floor laughing", keywords: ["rofl", "laugh", "lol", "funny"] },
      { char: "😂", name: "face with tears of joy", keywords: ["cry", "laugh", "lol", "funny", "tears"] },
      { char: "🙂", name: "slightly smiling face", keywords: ["smile", "slightly"] },
      { char: "🙃", name: "upside-down face", keywords: ["sarcasm", "silly", "upside down"] },
      { char: "😉", name: "winking face", keywords: ["wink", "flirt"] },
      { char: "😊", name: "smiling face with smiling eyes", keywords: ["smile", "happy", "blush"] },
      { char: "😇", name: "smiling face with halo", keywords: ["angel", "halo", "innocent"] },
      { char: "🥰", name: "smiling face with hearts", keywords: ["love", "hearts", "crush", "warm"] },
      { char: "😍", name: "smiling face with heart-eyes", keywords: ["love", "heart eyes", "adore"] },
      { char: "🤩", name: "star-struck", keywords: ["star eyes", "excited", "wow"] },
      { char: "😘", name: "face blowing a kiss", keywords: ["kiss", "love", "flirt"] },
      { char: "😗", name: "kissing face", keywords: ["kiss"] },
      { char: "😚", name: "kissing face with closed eyes", keywords: ["kiss", "love"] },
      { char: "😙", name: "kissing face with smiling eyes", keywords: ["kiss"] },
      { char: "😋", name: "face savoring food", keywords: ["yum", "delicious", "tongue", "hungry"] },
      { char: "😛", name: "face with tongue", keywords: ["tongue", "silly"] },
      { char: "😜", name: "winking face with tongue", keywords: ["wink", "tongue", "silly", "joke"] },
      { char: "🤪", name: "zany face", keywords: ["crazy", "silly", "goofy"] },
      { char: "😝", name: "squinting face with tongue", keywords: ["tongue", "silly", "squint"] },
      { char: "🤑", name: "money-mouth face", keywords: ["money", "rich", "dollar"] },
      { char: "🤗", name: "hugging face", keywords: ["hug", "warmth"] },
      { char: "🤭", name: "face with hand over mouth", keywords: ["gasp", "oops", "quiet"] },
      { char: "🤫", name: "shushing face", keywords: ["quiet", "shh", "silence"] },
      { char: "🤔", name: "thinking face", keywords: ["think", "ponder", "wonder", "hmm"] },
      { char: "🤐", name: "zipper-mouth face", keywords: ["zipper", "secret", "quiet"] },
      { char: "🤨", name: "face with raised eyebrow", keywords: ["suspicious", "doubt", "hmmm"] },
      { char: "😐", name: "neutral face", keywords: ["neutral", "meh", "okay"] },
      { char: "😑", name: "expressionless face", keywords: ["expressionless", "meh", "flat"] },
      { char: "😶", name: "face without mouth", keywords: ["silent", "speechless"] },
      { char: "😏", name: "smirking face", keywords: ["smirk", "sarcasm", "flirt"] },
      { char: "😒", name: "unamused face", keywords: ["unamused", "meh", "bored"] },
      { char: "🙄", name: "face with rolling eyes", keywords: ["roll eyes", "annoyed", "bored"] },
      { char: "😬", name: "grimacing face", keywords: ["grimace", "nervous", "awkward"] },
      { char: "🤥", name: "lying face", keywords: ["liar", "pinocchio", "fake"] },
      { char: "😌", name: "relieved face", keywords: ["relieved", "calm", "peace"] },
      { char: "😔", name: "pensive face", keywords: ["sad", "pensive", "sorry"] },
      { char: "😪", name: "sleepy face", keywords: ["sleepy", "tired"] },
      { char: "🤤", name: "drooling face", keywords: ["drool", "delicious", "sleepy"] },
      { char: "😴", name: "sleeping face", keywords: ["sleeping", "zzz", "tired"] },
      { char: "😷", name: "face with medical mask", keywords: ["mask", "sick", "virus"] },
      { char: "🤒", name: "face with thermometer", keywords: ["sick", "fever", "ill"] },
      { char: "🤕", name: "face with head-bandage", keywords: ["hurt", "injury", "accident"] },
      { char: "🤢", name: "nauseated face", keywords: ["sick", "gross", "vomit", "green"] },
      { char: "🤮", name: "face vomiting", keywords: ["vomit", "sick", "gross"] },
      { char: "🤧", name: "sneezing face", keywords: ["sneeze", "sick", "cold"] },
      { char: "🥵", name: "hot face", keywords: ["hot", "summer", "sweat", "spicy"] },
      { char: "🥶", name: "cold face", keywords: ["cold", "winter", "freeze", "ice"] },
      { char: "🥴", name: "woozy face", keywords: ["dizzy", "drunk", "woozy"] },
      { char: "😵", name: "dizzy face", keywords: ["dizzy", "dead", "knocked out"] },
      { char: "🤯", name: "exploding head", keywords: ["mind blown", "shock", "wow"] },
      { char: "🤠", name: "cowboy hat face", keywords: ["cowboy", "yeehaw", "hat"] },
      { char: "🥳", name: "partying face", keywords: ["party", "celebrate", "birthday"] },
      { char: "😎", name: "smiling face with sunglasses", keywords: ["cool", "glasses", "swag"] },
      { char: "🤓", name: "nerd face", keywords: ["nerd", "geek", "glasses", "smart"] },
      { char: "🧐", name: "face with monocle", keywords: ["monocle", "smart", "classy"] },
      { char: "😕", name: "confused face", keywords: ["confused", "huh", "doubt"] },
      { char: "😟", name: "worried face", keywords: ["worried", "nervous"] },
      { char: "🙁", name: "slightly frowning face", keywords: ["sad", "frown"] },
      { char: "😮", name: "face with open mouth", keywords: ["surprise", "gasp", "wow"] },
      { char: "😯", name: "hushed face", keywords: ["hushed", "quiet"] },
      { char: "😲", name: "astonished face", keywords: ["surprise", "shocked", "wow"] },
      { char: "😳", name: "flushed face", keywords: ["embarrassed", "flushed", "shame"] },
      { char: "🥺", name: "pleading face", keywords: ["plead", "puppy eyes", "beg"] },
      { char: "😦", name: "frowning face with open mouth", keywords: ["sad", "surprise"] },
      { char: "😧", name: "anguished face", keywords: ["sad", "pain"] },
      { char: "😨", name: "fearful face", keywords: ["fear", "scared", "shock"] },
      { char: "😰", name: "anxious face with sweat", keywords: ["anxious", "sweat", "nervous"] },
      { char: "😥", name: "sad but relieved face", keywords: ["sweat", "relieved", "nervous"] },
      { char: "😢", name: "crying face", keywords: ["cry", "sad", "tear"] },
      { char: "😭", name: "loudly crying face", keywords: ["cry", "sad", "sob", "bawl"] },
      { char: "😱", name: "face screaming in fear", keywords: ["scared", "scream", "fear", "shock"] },
      { char: "😖", name: "confounded face", keywords: ["confounded", "sad", "pain"] },
      { char: "😣", name: "persevering face", keywords: ["persevere", "struggle"] },
      { char: "😞", name: "disappointed face", keywords: ["sad", "disappointed"] },
      { char: "😓", name: "downcast face with sweat", keywords: ["sweat", "sad", "defeat"] },
      { char: "😩", name: "weary face", keywords: ["weary", "tired", "sad"] },
      { char: "😫", name: "tired face", keywords: ["tired", "weary", "sad"] },
      { char: "🥱", name: "yawning face", keywords: ["yawn", "tired", "sleepy"] },
      { char: "😤", name: "face with steam from nose", keywords: ["angry", "steam", "frustrated"] },
      { char: "😡", name: "pouting face", keywords: ["angry", "mad", "pout"] },
      { char: "😠", name: "angry face", keywords: ["angry", "mad", "annoyed"] },
      { char: "🤬", name: "face with symbols on mouth", keywords: ["swear", "curse", "angry", "mad"] },
      { char: "😈", name: "smiling face with horns", keywords: ["devil", "evil", "horns"] },
      { char: "👿", name: "angry face with horns", keywords: ["devil", "evil", "angry"] },
      { char: "💀", name: "skull", keywords: ["skull", "dead", "skeleton", "funny"] },
      { char: "💩", name: "pile of poo", keywords: ["poop", "poo", "turd"] },
      { char: "🤡", name: "clown face", keywords: ["clown", "circus", "silly"] },
      { char: "👹", name: "ogre", keywords: ["monster", "red", "ogre"] },
      { char: "👺", name: "goblin", keywords: ["monster", "red", "goblin"] },
      { char: "👻", name: "ghost", keywords: ["ghost", "spooky", "halloween"] },
      { char: "👽", name: "alien", keywords: ["alien", "ufo", "space"] },
      { char: "👾", name: "alien monster", keywords: ["pixel", "alien", "game"] },
      { char: "🤖", name: "robot", keywords: ["robot", "computer"] },
      { char: "👋", name: "waving hand", keywords: ["wave", "hello", "hi", "bye"] },
      { char: "🤚", name: "raised back of hand", keywords: ["backhand", "raised"] },
      { char: "🖐️", name: "hand with fingers splayed", keywords: ["hand", "splayed", "five"] },
      { char: "✋", name: "raised hand", keywords: ["stop", "raised", "five"] },
      { char: "🖖", name: "vulcan salute", keywords: ["spock", "vulcan", "salute", "star trek"] },
      { char: "👌", name: "OK hand", keywords: ["ok", "perfect", "agree"] },
      { char: "🤌", name: "pinched fingers", keywords: ["italian", "pinched", "what"] },
      { char: "🤏", name: "pinched hand", keywords: ["pinch", "small", "little"] },
      { char: "✌️", name: "victory hand", keywords: ["peace", "victory", "two"] },
      { char: "🤞", name: "crossed fingers", keywords: ["luck", "hope", "cross"] },
      { char: "🫰", name: "hand with index finger and thumb crossed", keywords: ["heart", "finger heart", "love"] },
      { char: "🤟", name: "love-you gesture", keywords: ["love", "ily", "gesture"] },
      { char: "🤘", name: "sign of the horns", keywords: ["rock on", "metal", "horns"] },
      { char: "🤙", name: "call me hand", keywords: ["call", "phone", "shaka"] },
      { char: "👈", name: "backhand index pointing left", keywords: ["point left", "left"] },
      { char: "👉", name: "backhand index pointing right", keywords: ["point right", "right"] },
      { char: "👆", name: "backhand index pointing up", keywords: ["point up", "up"] },
      { char: "🖕", name: "middle finger", keywords: ["middle finger", "flip off", "rude"] },
      { char: "👇", name: "backhand index pointing down", keywords: ["point down", "down"] },
      { char: "☝️", name: "index pointing up", keywords: ["point up", "one"] },
      { char: "👍", name: "thumbs up", keywords: ["thumbs up", "like", "agree", "yes"] },
      { char: "👎", name: "thumbs down", keywords: ["thumbs down", "dislike", "no"] },
      { char: "✊", name: "raised fist", keywords: ["fist", "power", "solidarity"] },
      { char: "👊", name: "oncoming fist", keywords: ["fist", "punch", "brofist"] },
      { char: "🤛", name: "left-facing fist", keywords: ["fist", "punch", "left"] },
      { char: "🤜", name: "right-facing fist", keywords: ["fist", "punch", "right"] },
      { char: "👏", name: "clapping hands", keywords: ["clap", "applause", "congrats"] },
      { char: "🙌", name: "raising hands", keywords: ["celebrate", "hooray", "hands"] },
      { char: "🫶", name: "heart hands", keywords: ["love", "heart", "hands"] },
      { char: "👐", name: "open hands", keywords: ["open", "hands", "hug"] },
      { char: "🤲", name: "palms up together", keywords: ["prayer", "cupped hands"] },
      { char: "🤝", name: "handshake", keywords: ["deal", "shake", "agree", "partner"] },
      { char: "🙏", name: "folded hands", keywords: ["pray", "please", "thanks", "hope"] },
      { char: "✍️", name: "writing hand", keywords: ["write", "pen"] },
      { char: "💅", name: "nail polish", keywords: ["nails", "polish", "beauty", "sass"] },
      { char: "🤳", name: "selfie", keywords: ["selfie", "camera", "phone"] },
      { char: "💪", name: "flexed biceps", keywords: ["muscle", "flex", "strong", "power"] },
      { char: "🧠", name: "brain", keywords: ["brain", "think", "smart"] },
      { char: "👀", name: "eyes", keywords: ["look", "see", "watching", "eyes"] }
    ]
  },
  {
    id: "nature",
    name: "Animals & Nature",
    icon: "🐶",
    emojis: [
      { char: "🐶", name: "dog face", keywords: ["dog", "puppy", "pet", "bark"] },
      { char: "🐱", name: "cat face", keywords: ["cat", "kitten", "pet", "meow"] },
      { char: "🐭", name: "mouse face", keywords: ["mouse", "rodent"] },
      { char: "🐹", name: "hamster face", keywords: ["hamster", "pet"] },
      { char: "🐰", name: "rabbit face", keywords: ["rabbit", "bunny", "pet"] },
      { char: "🦊", name: "fox", keywords: ["fox", "wildlife"] },
      { char: "🐻", name: "bear", keywords: ["bear", "wildlife"] },
      { char: "🐼", name: "panda", keywords: ["panda", "bear"] },
      { char: "🐻‍❄️", name: "polar bear", keywords: ["polar", "bear", "ice"] },
      { char: "🐨", name: "koala", keywords: ["koala", "australia"] },
      { char: "🐯", name: "tiger face", keywords: ["tiger", "wildlife", "roar"] },
      { char: "🦁", name: "lion", keywords: ["lion", "king", "roar"] },
      { char: "🐮", name: "cow face", keywords: ["cow", "farm", "moo"] },
      { char: "🐷", name: "pig face", keywords: ["pig", "farm", "oink"] },
      { char: "🐸", name: "frog", keywords: ["frog", "toad", "ribbit"] },
      { char: "🐵", name: "monkey face", keywords: ["monkey", "chimp"] },
      { char: "🙈", name: "see-no-evil monkey", keywords: ["monkey", "blind", "hide"] },
      { char: "🙉", name: "hear-no-evil monkey", keywords: ["monkey", "deaf", "quiet"] },
      { char: "🙊", name: "speak-no-evil monkey", keywords: ["monkey", "mute", "secret"] },
      { char: "🐔", name: "chicken", keywords: ["chicken", "cluck"] },
      { char: "🐧", name: "penguin", keywords: ["penguin", "ice", "bird"] },
      { char: "🦅", name: "eagle", keywords: ["eagle", "bird", "usa"] },
      { char: "🦉", name: "owl", keywords: ["owl", "bird", "wise"] },
      { char: "🦇", name: "bat", keywords: ["bat", "spooky", "vampire"] },
      { char: "🐺", name: "wolf", keywords: ["wolf", "wildlife", "howl"] },
      { char: "🐗", name: "boar", keywords: ["boar", "wildlife"] },
      { char: "🐴", name: "horse face", keywords: ["horse", "farm", "neigh"] },
      { char: "🦄", name: "unicorn", keywords: ["unicorn", "magic", "fantasy"] },
      { char: "🐝", name: "honeybee", keywords: ["bee", "honey", "buzz"] },
      { char: "🐛", name: "bug", keywords: ["caterpillar", "bug", "insect"] },
      { char: "🦋", name: "butterfly", keywords: ["butterfly", "insect", "wings"] },
      { char: "🐌", name: "snail", keywords: ["snail", "slow", "shell"] },
      { char: "🐞", name: "lady beetle", keywords: ["ladybug", "insect"] },
      { char: "🐜", name: "ant", keywords: ["ant", "insect"] },
      { char: "🕷️", name: "spider", keywords: ["spider", "insect", "spooky"] },
      { char: "🦂", name: "scorpion", keywords: ["scorpion", "spooky", "sting"] },
      { char: "🐢", name: "turtle", keywords: ["turtle", "slow", "shell"] },
      { char: "🐍", name: "snake", keywords: ["snake", "hiss", "reptile"] },
      { char: " Octopus: 🐙", name: "octopus", keywords: ["octopus", "sea", "ocean"] },
      { char: "🦑", name: "squid", keywords: ["squid", "sea", "ocean"] },
      { char: "🦞", name: "lobster", keywords: ["lobster", "seafood"] },
      { char: "🦀", name: "crab", keywords: ["crab", "seafood"] },
      { char: "🐬", name: "dolphin", keywords: ["dolphin", "sea", "ocean"] },
      { char: "🐳", name: "spouting whale", keywords: ["whale", "sea", "ocean"] },
      { char: "🦈", name: "shark", keywords: ["shark", "sea", "ocean", "jaws"] },
      { char: "🌴", name: "palm tree", keywords: ["palm", "tree", "beach", "summer"] },
      { char: "🌲", name: "evergreen tree", keywords: ["pine", "tree", "forest"] },
      { char: "🍁", name: "maple leaf", keywords: ["maple", "leaf", "autumn", "canada"] },
      { char: "🌹", name: "rose", keywords: ["rose", "flower", "love", "red"] },
      { char: "🌻", name: "sunflower", keywords: ["sunflower", "flower", "yellow"] },
      { char: "🌷", name: "tulip", keywords: ["tulip", "flower", "spring"] },
      { char: "🌸", name: "cherry blossom", keywords: ["cherry blossom", "flower", "pink"] },
      { char: "🍀", name: "four leaf clover", keywords: ["clover", "luck", "green"] },
      { char: "🌵", name: "cactus", keywords: ["cactus", "desert", "green"] },
      { char: "🌾", name: "sheaf of rice", keywords: ["rice", "grain"] },
      { char: "🌿", name: "herb", keywords: ["herb", "green", "plant"] }
    ]
  },
  {
    id: "food",
    name: "Food & Drink",
    icon: "🍏",
    emojis: [
      { char: "🍏", name: "green apple", keywords: ["apple", "green", "fruit"] },
      { char: "🍎", name: "red apple", keywords: ["apple", "red", "fruit"] },
      { char: "🍐", name: "pear", keywords: ["pear", "fruit"] },
      { char: "🍊", name: "tangerine", keywords: ["orange", "citrus", "fruit"] },
      { char: "🍋", name: "lemon", keywords: ["lemon", "citrus", "fruit"] },
      { char: "🍌", name: "banana", keywords: ["banana", "fruit", "yellow"] },
      { char: "🍉", name: "watermelon", keywords: ["watermelon", "fruit", "summer"] },
      { char: "🍇", name: "grapes", keywords: ["grapes", "fruit"] },
      { char: "🍓", name: "strawberry", keywords: ["strawberry", "fruit", "berry"] },
      { char: "🫐", name: "blueberries", keywords: ["blueberries", "fruit", "berry"] },
      { char: "🍒", name: "cherries", keywords: ["cherries", "fruit"] },
      { char: "🍑", name: "peach", keywords: ["peach", "fruit"] },
      { char: "🍍", name: "pineapple", keywords: ["pineapple", "fruit"] },
      { char: "🥥", name: "coconut", keywords: ["coconut", "fruit"] },
      { char: "🥝", name: "kiwi fruit", keywords: ["kiwi", "fruit"] },
      { char: "🍅", name: "tomato", keywords: ["tomato", "fruit", "vegetable"] },
      { char: "🥑", name: "avocado", keywords: ["avocado", "fruit", "healthy"] },
      { char: "🍆", name: "eggplant", keywords: ["eggplant", "vegetable"] },
      { char: "🥔", name: "potato", keywords: ["potato", "vegetable"] },
      { char: "🥕", name: "carrot", keywords: ["carrot", "vegetable"] },
      { char: "🌽", name: "ear of corn", keywords: ["corn", "vegetable"] },
      { char: "🌶️", name: "hot pepper", keywords: ["chili", "pepper", "spicy"] },
      { char: "🧀", name: "cheese wedge", keywords: ["cheese", "dairy"] },
      { char: "🍞", name: "bread", keywords: ["bread", "toast", "bakery"] },
      { char: "🥐", name: "croissant", keywords: ["croissant", "bread", "bakery"] },
      { char: "🍖", name: "meat on bone", keywords: ["meat", "bone", "bbq"] },
      { char: "🍗", name: "poultry leg", keywords: ["chicken", "drumstick", "meat"] },
      { char: "🍔", name: "hamburger", keywords: ["burger", "hamburger", "fast food"] },
      { char: "🍟", name: "french fries", keywords: ["fries", "french fries", "fast food"] },
      { char: "🍕", name: "pizza", keywords: ["pizza", "cheese", "fast food"] },
      { char: "🌭", name: "hot dog", keywords: ["hotdog", "fast food"] },
      { char: "🥪", name: "sandwich", keywords: ["sandwich", "bread", "lunch"] },
      { char: "🍳", name: "cooking", keywords: ["egg", "frying pan", "breakfast"] },
      { char: "🍿", name: "popcorn", keywords: ["popcorn", "movie", "snack"] },
      { char: "🍱", name: "bento box", keywords: ["bento", "sushi", "japanese"] },
      { char: "🍣", name: "sushi", keywords: ["sushi", "fish", "japanese"] },
      { char: "🍦", name: "soft ice cream", keywords: ["ice cream", "soft serve", "dessert"] },
      { char: "🍧", name: "shaved ice", keywords: ["shaved ice", "dessert"] },
      { char: "🍩", name: "donut", keywords: ["donut", "doughnut", "dessert", "sweet"] },
      { char: "🍪", name: "cookie", keywords: ["cookie", "biscuit", "dessert", "chocolate"] },
      { char: "🎂", name: "birthday cake", keywords: ["cake", "birthday", "dessert", "sweet"] },
      { char: "🍫", name: "chocolate bar", keywords: ["chocolate", "candy", "sweet"] },
      { char: "🍬", name: "candy", keywords: ["candy", "sweet"] },
      { char: "🍯", name: "honey pot", keywords: ["honey", "sweet"] },
      { char: "☕", name: "hot beverage", keywords: ["coffee", "tea", "cafe", "hot"] },
      { char: "🍵", name: "teacup without handle", keywords: ["tea", "matcha", "green tea"] },
      { char: "🍶", name: "sake", keywords: ["sake", "alcohol", "drink"] },
      { char: "🍾", name: "bottle with popping cork", keywords: ["champagne", "wine", "alcohol", "celebrate"] },
      { char: "🍷", name: "wine glass", keywords: ["wine", "alcohol", "drink"] },
      { char: "🍸", name: "cocktail glass", keywords: ["cocktail", "alcohol", "drink"] },
      { char: "🍹", name: "tropical drink", keywords: ["cocktail", "tropical", "summer", "drink"] },
      { char: "🍺", name: "beer mug", keywords: ["beer", "alcohol", "drink"] },
      { char: "🍻", name: "clinking beer mugs", keywords: ["beers", "cheers", "alcohol", "drink"] },
      { char: "🥤", name: "cup with straw", keywords: ["soda", "straw", "drink"] }
    ]
  },
  {
    id: "activity",
    name: "Activity",
    icon: "⚽",
    emojis: [
      { char: "⚽", name: "soccer ball", keywords: ["soccer", "football", "ball", "sport"] },
      { char: "🏀", name: "basketball", keywords: ["basketball", "ball", "sport"] },
      { char: "🏈", name: "american football", keywords: ["football", "sport"] },
      { char: "⚾", name: "baseball", keywords: ["baseball", "ball", "sport"] },
      { char: "🥎", name: "softball", keywords: ["softball", "ball", "sport"] },
      { char: "🎾", name: "tennis", keywords: ["tennis", "racket", "ball", "sport"] },
      { char: " Volleyball: 🏐", name: "volleyball", keywords: ["volleyball", "ball", "sport"] },
      { char: "🎱", name: "pool 8 ball", keywords: ["pool", "billiards", "ball", "sport"] },
      { char: "⛳", name: "flag in hole", keywords: ["golf", "flag", "sport"] },
      { char: "🏓", name: "ping pong", keywords: ["ping pong", "table tennis", "racket", "sport"] },
      { char: "🏸", name: "badminton", keywords: ["badminton", "racket", "sport"] },
      { char: "🥊", name: "boxing glove", keywords: ["boxing", "glove", "sport"] },
      { char: "🥋", name: "martial arts uniform", keywords: ["karate", "judo", "uniform", "sport"] },
      { char: "🏆", name: "trophy", keywords: ["trophy", "winner", "prize", "first"] },
      { char: "🥇", name: "1st place medal", keywords: ["medal", "gold", "first"] },
      { char: "🥈", name: "2nd place medal", keywords: ["medal", "silver", "second"] },
      { char: "🥉", name: "3rd place medal", keywords: ["medal", "bronze", "third"] },
      { char: "🎖️", name: "military medal", keywords: ["medal", "military", "honor"] },
      { char: "🎗️", name: "reminder ribbon", keywords: ["ribbon", "awareness"] },
      { char: "🎫", name: "ticket", keywords: ["ticket", "show", "admission"] },
      { char: "🎟️", name: "admission tickets", keywords: ["tickets", "show", "admission"] },
      { char: "🎮", name: "video game", keywords: ["game", "controller", "playstation", "xbox"] },
      { char: "🎯", name: "bullseye", keywords: ["darts", "target", "bullseye", "focus"] },
      { char: "🎲", name: "game die", keywords: ["dice", "die", "board game", "luck"] },
      { char: "🧩", name: "puzzle piece", keywords: ["puzzle", "jigsaw", "piece"] },
      { char: "🎨", name: "artist palette", keywords: ["paint", "art", "palette", "draw"] },
      { char: "🎬", name: "clapper board", keywords: ["movie", "clapper", "film", "cinema"] }
    ]
  },
  {
    id: "places",
    name: "Travel & Places",
    icon: "🚗",
    emojis: [
      { char: "🚗", name: "automobile", keywords: ["car", "automobile", "drive", "travel"] },
      { char: "🚕", name: "taxi", keywords: ["taxi", "cab", "ride", "travel"] },
      { char: "🚙", name: "sport utility vehicle", keywords: ["car", "suv", "drive", "travel"] },
      { char: "🚌", name: "bus", keywords: ["bus", "ride", "travel"] },
      { char: "🚲", name: "bicycle", keywords: ["bike", "bicycle", "cycle", "ride"] },
      { char: "🛵", name: "motor scooter", keywords: ["scooter", "vespa", "ride"] },
      { char: "🏍️", name: "motorcycle", keywords: ["motorcycle", "bike", "ride"] },
      { char: "🚨", name: "police car light", keywords: ["siren", "police", "emergency", "alert", "warning"] },
      { char: "🚓", name: "police car", keywords: ["police", "car", "cop"] },
      { char: "🚀", name: "rocket", keywords: ["rocket", "space", "launch", "fast", "fly"] },
      { char: "✈️", name: "airplane", keywords: ["plane", "airplane", "flight", "travel"] },
      { char: "🛸", name: "flying saucer", keywords: ["ufo", "alien", "space"] },
      { char: "🚢", name: "ship", keywords: ["ship", "boat", "cruise", "travel"] },
      { char: "⚓", name: "anchor", keywords: ["anchor", "boat", "sea"] },
      { char: "🗺️", name: "world map", keywords: ["map", "world", "travel", "explore"] },
      { char: "🗿", name: "moai", keywords: ["statue", "easter island", "moai"] },
      { char: "🗽", name: "Statue of Liberty", keywords: ["statue", "liberty", "usa", "new york"] },
      { char: "🗼", name: "Tokyo Tower", keywords: ["tower", "tokyo", "japan"] },
      { char: "🏰", name: "castle", keywords: ["castle", "disney", "palace"] },
      { char: "⛺", name: "tent", keywords: ["tent", "camp", "outdoor"] },
      { char: "🏠", name: "house", keywords: ["house", "home", "building"] },
      { char: "🏢", name: "office building", keywords: ["office", "building", "work"] },
      { char: "🏫", name: "school", keywords: ["school", "education", "building"] },
      { char: "🏛️", name: "classical building", keywords: ["classical", "museum", "temple", "court"] },
      { char: "⛪", name: "church", keywords: ["church", "religion", "building"] },
      { char: "🕌", name: "mosque", keywords: ["mosque", "islam", "religion"] },
      { char: "⛰️", name: "mountain", keywords: ["mountain", "nature", "outdoor"] },
      { char: "🌋", name: "volcano", keywords: ["volcano", "lava", "hot"] },
      { char: "🏖️", name: "beach with umbrella", keywords: ["beach", "umbrella", "summer", "sand"] },
      { char: "🏝️", name: "desert island", keywords: ["island", "beach", "summer", "ocean"] }
    ]
  },
  {
    id: "objects",
    name: "Objects",
    icon: "⌚",
    emojis: [
      { char: "⌚", name: "watch", keywords: ["watch", "time", "clock"] },
      { char: "📱", name: "mobile phone", keywords: ["phone", "mobile", "smartphone", "iphone"] },
      { char: "💻", name: "laptop", keywords: ["laptop", "computer", "pc", "macbook", "work"] },
      { char: "🖥️", name: "desktop computer", keywords: ["computer", "desktop", "pc", "screen"] },
      { char: "⌨️", name: "keyboard", keywords: ["keyboard", "computer"] },
      { char: "🖱️", name: "computer mouse", keywords: ["mouse", "computer"] },
      { char: "💿", name: "optical disk", keywords: ["cd", "dvd", "disk"] },
      { char: "💾", name: "floppy disk", keywords: ["floppy", "disk", "save"] },
      { char: "📸", name: "camera with flash", keywords: ["camera", "photo", "flash"] },
      { char: "📞", name: "telephone receiver", keywords: ["phone", "call", "telephone"] },
      { char: "📠", name: "fax machine", keywords: ["fax", "machine"] },
      { char: "📺", name: "television", keywords: ["tv", "television", "screen"] },
      { char: "🎙️", name: "studio microphone", keywords: ["microphone", "mic", "record", "podcast"] },
      { char: "⏰", name: "alarm clock", keywords: ["clock", "alarm", "time"] },
      { char: "⌛", name: "hourglass done", keywords: ["hourglass", "time", "wait"] },
      { char: "⏳", name: "hourglass not done", keywords: ["hourglass", "time", "wait", "loading"] },
      { char: "💡", name: "light bulb", keywords: ["light", "bulb", "idea", "smart"] },
      { char: "💵", name: "dollar banknote", keywords: ["dollar", "money", "cash", "rich"] },
      { char: "🪙", name: "coin", keywords: ["coin", "money", "gold", "silver"] },
      { char: "💰", name: "money bag", keywords: ["money bag", "money", "cash", "wealth"] },
      { char: "💳", name: "credit card", keywords: ["card", "credit", "money", "payment"] },
      { char: "💎", name: "gem stone", keywords: ["gem", "diamond", "jewelry", "rich"] },
      { char: "⚖️", name: "balance scale", keywords: ["scale", "justice", "law"] },
      { char: "🔧", name: "wrench", keywords: ["wrench", "tool", "fix", "repair"] },
      { char: "🔨", name: "hammer", keywords: ["hammer", "tool", "build", "fix"] },
      { char: "⚙️", name: "gear", keywords: ["gear", "cog", "settings", "operations"] },
      { char: "⛓️", name: "chains", keywords: ["chains", "link", "locked"] },
      { char: "🔫", name: "water pistol", keywords: ["gun", "pistol", "water gun", "squirt gun"] },
      { char: "💣", name: "bomb", keywords: ["bomb", "exploding", "danger"] },
      { char: "🔑", name: "key", keywords: ["key", "lock", "password", "secure"] },
      { char: "🔒", name: "locked", keywords: ["locked", "padlock", "secure", "private"] },
      { char: "🔓", name: "unlocked", keywords: ["unlocked", "padlock", "open", "public"] },
      { char: "📦", name: "package", keywords: ["package", "box", "parcel", "delivery"] },
      { char: "✉️", name: "envelope", keywords: ["envelope", "letter", "mail", "email"] },
      { char: "📧", name: "e-mail", keywords: ["email", "mail", "letter"] },
      { char: "📂", name: "open file folder", keywords: ["folder", "directory", "file"] },
      { char: "📁", name: "file folder", keywords: ["folder", "directory", "file"] },
      { char: "📅", name: "calendar", keywords: ["calendar", "date", "schedule"] },
      { char: "📊", name: "bar chart", keywords: ["chart", "bar", "graph", "stats", "data"] },
      { char: "📈", name: "chart increasing", keywords: ["chart", "graph", "up", "growth"] },
      { char: "📎", name: "paperclip", keywords: ["paperclip", "attach", "attachment", "file"] },
      { char: "🗑️", name: "wastebasket", keywords: ["trash", "bin", "garbage", "delete"] }
    ]
  },
  {
    id: "symbols",
    name: "Symbols",
    icon: "❤️",
    emojis: [
      { char: "❤️", name: "red heart", keywords: ["heart", "love", "red"] },
      { char: "🧡", name: "orange heart", keywords: ["heart", "orange", "love"] },
      { char: "💛", name: "yellow heart", keywords: ["heart", "yellow", "love"] },
      { char: "💚", name: "green heart", keywords: ["heart", "green", "love"] },
      { char: "💙", name: "blue heart", keywords: ["heart", "blue", "love"] },
      { char: "💜", name: "purple heart", keywords: ["heart", "purple", "love"] },
      { char: "🖤", name: "black heart", keywords: ["heart", "black", "love"] },
      { char: "🤍", name: "white heart", keywords: ["heart", "white", "love"] },
      { char: "💔", name: "broken heart", keywords: ["heart", "broken", "sad"] },
      { char: "💤", name: "zzz", keywords: ["sleep", "zzz", "tired", "dnd"] },
      { char: "⚠️", name: "warning", keywords: ["warning", "alert", "danger", "caution"] },
      { char: "⛔", name: "no entry", keywords: ["stop", "no entry", "forbidden"] },
      { char: "🚫", name: "prohibited", keywords: ["stop", "prohibited", "no"] },
      { char: "💯", name: "hundred points", keywords: ["100", "perfect", "deal"] },
      { char: "📢", name: "megaphone", keywords: ["megaphone", "broadcast", "announcement"] },
      { char: "🔔", name: "bell", keywords: ["bell", "notification", "ring"] },
      { char: "🔕", name: "bell with slash", keywords: ["bell", "mute", "silent", "dnd"] },
      { char: "➕", name: "plus", keywords: ["plus", "add", "math"] },
      { char: "➖", name: "minus", keywords: ["minus", "subtract", "math"] },
      { char: "✖️", name: "multiply", keywords: ["multiply", "times", "math"] },
      { char: "➗", name: "divide", keywords: ["divide", "math"] },
      { char: "♾️", name: "infinity", keywords: ["infinity", "forever"] },
      { char: "⚪", name: "white circle", keywords: ["circle", "white"] },
      { char: "⚫", name: "black circle", keywords: ["circle", "black"] },
      { char: "🔴", name: "red circle", keywords: ["circle", "red", "critical"] },
      { char: "🔵", name: "blue circle", keywords: ["circle", "blue", "requests"] }
    ]
  },
  {
    id: "flags",
    name: "Flags",
    icon: "🏁",
    emojis: [
      { char: "🏁", name: "chequered flag", keywords: ["race", "finish", "flag"] },
      { char: "🚩", name: "triangular flag", keywords: ["flag", "mark", "warning"] },
      { char: "🇺🇸", name: "United States", keywords: ["usa", "united states", "flag"] },
      { char: "🇬🇧", name: "United Kingdom", keywords: ["uk", "united kingdom", "flag", "gb"] },
      { char: "🇨🇦", name: "Canada", keywords: ["canada", "flag"] },
      { char: "🇩🇪", name: "Germany", keywords: ["germany", "flag"] },
      { char: "🇫🇷", name: "France", keywords: ["france", "flag"] },
      { char: "🇯🇵", name: "Japan", keywords: ["japan", "flag"] },
      { char: "🇵🇰", name: "Pakistan", keywords: ["pakistan", "flag"] },
      { char: "🇮🇳", name: "India", keywords: ["india", "flag"] },
      { char: "🇪🇺", name: "European Union", keywords: ["eu", "flag"] }
    ]
  }
];
